/**
 * Every piece of copy and every link on the site lives in this file.
 * Edit here, not inside the components.
 *
 * Rule for this file: each claim should be something you can explain in an
 * interview without notes. If you can't defend a line, cut it.
 */

export const profile = {
  name: "Chaitanya Virani",
  tagline: "An AI engineer obsessed with agents that act",
  status: "Final-year ICT student at PDEU, Ahmedabad. Open to AI engineering roles from 2027.",
  about:
    "I'm a final-year ICT student at PDEU who builds AI systems that act, and I care most about the unglamorous part: checking what a model returns before anything downstream trusts it. This summer I shipped production tools for real clients as an AI Engineer Intern at Clarivis Intelligence.",
  email: "chaitanyavirani125@gmail.com",
  github: "https://github.com/Chaitanya-Virani",
  linkedin: "https://www.linkedin.com/in/chaitanyavirani/",
  // Must match the file in public/ exactly (Vercel paths are case-sensitive).
  // Set to "" to hide every Resume link.
  resume: "/Chaitanya_resume.pdf",
};

export type Highlight = {
  title: string;
  text: string;
  href?: string;
};

export const experience = {
  org: "Clarivis Intelligence",
  role: "AI Engineer Intern",
  period: "May to July 2026",
  summary:
    "AI consulting firm. I shipped platforms for Clarivis clients and built the firm's internal AI tooling.",
  highlights: [
    {
      title: "Chitrini Natyam",
      href: "https://chitrininatyam.com",
      text: "Owned the full stack of a live dance-academy platform running in Tokyo and Ahmedabad: region-isolated admin data with Postgres row-level security, rolling class schedules generated by pg_cron, and booking emails with calendar invites.",
    },
    {
      title: "Minutely",
      href: "#project-minutely",
      text: "Meeting-report generator built on Claude tool use, with every model response validated before a PDF is rendered. Full write-up in Projects.",
    },
    {
      title: "Blog publishing pipeline",
      text: "n8n workflow that drafts posts, waits for approval over Telegram, writes to Supabase, and triggers a Vercel rebuild through a deploy hook.",
    },
    {
      title: "AXIOT and SkyAI website rebuilds",
      text: "Led redesigns of two client marketing sites, a B2B IoT platform and an AI services company, built with Claude Design and Claude Code and deployed on Vercel.",
    },
  ] as Highlight[],
};

export const recognition = [
  {
    label: "Code with Cisco 2026",
    text: "Team lead. Cleared the online assessment and the onsite hackathon in Bengaluru, finishing in the national top 75.",
  },
  {
    label: "HackNUthon",
    text: "6th place.",
  },
  {
    label: "Robotics club, PDEU",
    text: "Co-Head of Software. Led four junior members and built a self-balancing robot for the techfest.",
  },
  {
    label: "Education",
    text: "B.Tech in Information and Communication Technology, PDEU, class of 2027, CGPA 8.52. Lateral entry after a diploma in computer engineering.",
  },
];

export type Specimen = "minutely" | "cits" | "esp32";

export type Project = {
  id: string;
  number: string;
  category: string;
  title: string;
  summary: string;
  details: string[];
  stack: string[];
  githubHref?: string;
  liveHref?: string;
  liveNote?: string;
  specimen: Specimen;
};

export const projects: Project[] = [
  {
    id: "project-minutely",
    number: "01",
    category: "Built at Clarivis",
    title: "Minutely",
    summary:
      "Turns a raw meeting transcript into a structured PDF report: decisions, action items with owners, risks, and key dates.",
    details: [
      "One Claude call using tool use, with the response validated against a Pydantic schema before anything is rendered.",
      "When production responses came back as objects where strings were expected, a before-mode validator coerces them instead of failing the request.",
      "Stateless by design: no database, PDFs rendered in memory with ReportLab, two Docker services on Railway.",
    ],
    stack: ["FastAPI", "Claude API", "Pydantic", "ReportLab", "Next.js", "Docker", "Railway"],
    githubHref: "https://github.com/Chaitanya-Virani/Minutely",
    liveHref: "https://frontend-production-9e699.up.railway.app/",
    specimen: "minutely",
  },
  {
    id: "project-cits",
    number: "02",
    category: "Personal",
    title: "Customer Insight Triage System",
    summary:
      "Reads Indian e-commerce reviews, including Hinglish, and flags the ones a human needs to see right now.",
    details: [
      "TF-IDF with bigrams and logistic regression for sentiment, backed by a rule layer that catches fraud, damage, and return complaints the model can miss.",
      "Admin dashboard with evaluation metrics, drift detection against historical sentiment, and one-click retraining that compares a candidate model with the current one.",
      "FastAPI, SQLAlchemy, and Pydantic v2 over a SQLite store seeded with 145+ products.",
    ],
    stack: ["FastAPI", "scikit-learn", "SQLAlchemy", "Pydantic", "SQLite", "Render"],
    githubHref: "https://github.com/Chaitanya-Virani/CITS",
    liveHref: "https://cits-u9pn.onrender.com/",
    liveNote: "Hosted on Render's free tier, so the first load can take about 30 seconds.",
    specimen: "cits",
  },
  {
    id: "project-esp32",
    number: "03",
    category: "Personal",
    title: "ESP32 Wireless Walkie-Talkie",
    summary:
      "Two ESP32 boards that talk to each other directly over ESP-NOW. No router, no internet, no pairing.",
    details: [
      "Push-to-talk, half-duplex audio at 8 kHz, packed 100 samples to a packet.",
      "Cut the send rate from 1,600 to 80 packets a second, which took delivery from about 60% to about 95%.",
      "Jitter buffer with pre-roll for steady playback, plus a DSP chain: DC offset removal, high- and low-pass filters, noise gate, and automatic gain control.",
    ],
    stack: ["ESP32", "ESP-NOW", "C++", "FreeRTOS", "Arduino"],
    githubHref: "https://github.com/Chaitanya-Virani/ESP32_WALKIE-TALKIE",
    specimen: "esp32",
  },
];

export type Capability = {
  title: string;
  description: string;
  proof: { label: string; href: string }[];
};

export const capabilities: Capability[] = [
  {
    title: "Validated LLM output",
    description:
      "Claude tool use with schema validation, so a model's answer is checked before anything downstream relies on it.",
    proof: [{ label: "Minutely", href: "#project-minutely" }],
  },
  {
    title: "ML backends",
    description:
      "FastAPI and scikit-learn services with evaluation metrics, drift detection, and retraining built in.",
    proof: [{ label: "Customer Insight Triage System", href: "#project-cits" }],
  },
  {
    title: "Embedded systems",
    description:
      "ESP32 firmware for real-time audio: radio links, buffering, and signal filtering on constrained hardware.",
    proof: [{ label: "ESP32 walkie-talkie", href: "#project-esp32" }],
  },
  {
    title: "Automation pipelines",
    description:
      "Workflows that connect models, databases, and deploys, with a human approval step where it matters.",
    proof: [{ label: "Clarivis blog pipeline", href: "#experience" }],
  },
  {
    title: "Production platforms",
    description:
      "Postgres with row-level security, scheduled jobs, and transactional email, shipped for real users in two countries.",
    proof: [{ label: "Chitrini Natyam", href: "#experience" }],
  },
];

/**
 * Tools shown in the logo strip. Keep this to things you have used in a
 * shipped project and can answer questions about.
 * `slug` must exist in simple-icons 16.32.0 (https://simpleicons.org).
 */
export const tools = [
  { name: "Python", slug: "python" },
  { name: "FastAPI", slug: "fastapi" },
  { name: "Pydantic", slug: "pydantic" },
  { name: "Anthropic API", slug: "anthropic" },
  { name: "scikit-learn", slug: "scikitlearn" },
  { name: "pandas", slug: "pandas" },
  { name: "SQLAlchemy", slug: "sqlalchemy" },
  { name: "PostgreSQL", slug: "postgresql" },
  { name: "Supabase", slug: "supabase" },
  { name: "Docker", slug: "docker" },
  { name: "GitHub Actions", slug: "githubactions" },
  { name: "Railway", slug: "railway" },
  { name: "Vercel", slug: "vercel" },
  { name: "n8n", slug: "n8n" },
  { name: "ESP32", slug: "espressif" },
  { name: "Arduino", slug: "arduino" },
  { name: "C++", slug: "cplusplus" },
  { name: "Git", slug: "git" },
];
